INC_DIRS    += ./HAL/inc
SRC_DIRS	+= ./HAL/src

SRC_FILES   += ./HAL/src/stm32_hal_gpio.c
SRC_FILES   += ./HAL/src/stm32_hal_i2c.c
SRC_FILES   += ./HAL/src/stm32_hal_rcc.c
SRC_FILES   += ./HAL/src/stm32_hal_spi.c
SRC_FILES   += ./HAL/src/stm32_hal_usb.c
SRC_FILES   += ./HAL/src/stm32_usb_hid.c