INC_DIRS    += ./APP/src
SRC_DIRS	+= ./APP/src

SRC_FILES   += ./APP/src/button.c
SRC_FILES   += ./APP/src/custom_font.c
SRC_FILES   += ./APP/src/fonts.c
SRC_FILES   += ./APP/src/lcd_generic.c
SRC_FILES   += ./APP/src/led_rgb.c
SRC_FILES   += ./APP/src/main.c
SRC_FILES   += ./APP/src/oled_bitmap.c
SRC_FILES   += ./APP/src/oled.c
SRC_FILES   += ./APP/src/spiflash.c
SRC_FILES   += ./APP/src/uart_ring_buffer.c