INC_DIRS    += ./FreeRTOS/include
INC_DIRS    += ./FreeRTOS/portable/GCC/ARM_CM3
SRC_DIRS	+= ./FreeRTOS
SRC_DIRS	+= ./FreeRTOS/portable/MemMang
SRC_DIRS	+= ./FreeRTOS/portable/GCC/ARM_CM3

SRC_FILES   += ./FreeRTOS/croutine.c
SRC_FILES   += ./FreeRTOS/event_groups.c
SRC_FILES   += ./FreeRTOS/list.c
SRC_FILES   += ./FreeRTOS/queue.c
SRC_FILES   += ./FreeRTOS/stream_buffer.c
SRC_FILES   += ./FreeRTOS/tasks.c
SRC_FILES   += ./FreeRTOS/timers.c
SRC_FILES   += ./FreeRTOS/portable/MemMang/heap_4.c
SRC_FILES   += ./FreeRTOS/portable/GCC/ARM_CM3/port.c