INC_DIRS    += ./Driver/inc
SRC_DIRS	+= ./Driver/src

SRC_FILES   += ./Driver/src/stm32_driver_gpio.c
SRC_FILES   += ./Driver/src/stm32_driver_rcc.c
SRC_FILES   += ./Driver/src/stm32_driver_i2c.c
SRC_FILES   += ./Driver/src/stm32_driver_spi.c
SRC_FILES   += ./Driver/src/stm32_driver_tim.c
SRC_FILES   += ./Driver/src/stm32_driver_uart.c
SRC_FILES   += ./Driver/src/stm32_interrupt.c